jobs:
  # This will build an IPA & Upload the artifact in iOS.zip
  build-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Build iOS with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.IONIC_TOKEN }}
          app-id: mygusbetabuild
          platform: iOS
          build-type: ad-hoc
          environment: MyEnv
          native-config: MyNativeConfig
          certificate: MyCertificate
          build-stack: macOS - 2020.09
          upload-artifact: iOS